{% set version = '5.1-0' %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-gamlss.dist
  version: {{ version|replace("-", "_") }}

source:
  fn: gamlss.dist_{{ version }}.tar.gz
  url:
    - {{ cran_mirror }}/src/contrib/gamlss.dist_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/gamlss.dist/gamlss.dist_{{ version }}.tar.gz
  sha256: acb9e2aacceb7bda9e0b716fea851b9c245cee7f63ed5f1cb00113ae033dd731

build:
  merge_build_host: True  # [win]
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}        # [not win]
    - {{native}}toolchain        # [win]
    - {{posix}}filesystem        # [win]
    - {{posix}}make
    - {{posix}}sed               # [win]
    - {{posix}}coreutils         # [win]
    - {{posix}}zip               # [win]

  host:
    - r-base
    - r-mass

  run:
    - r-base
    - {{native}}gcc-libs         # [win]
    - r-mass

test:
  commands:
    - $R -e "library('gamlss.dist')"           # [not win]
    - "\"%R%\" -e \"library('gamlss.dist')\""  # [win]

about:
  home: http://www.gamlss.org/
  license: GPL-2 | GPL-3
  summary: 'A set of distributions  which can be used  for modelling the response variables in
    Generalized Additive Models for Location Scale and Shape, Rigby and Stasinopoulos
    (2005), <doi:10.1111/j.1467-9876.2005.00510.x>. The distributions can be continuous,
    discrete or mixed  distributions.  Extra distributions can be created, by transforming,
    any continuous distribution defined on the real line,  to  a distribution defined
    on ranges 0 to infinity  or  0 to 1,  by using a ''''log'''' or a ''''logit'' transformation
    respectively. '

  license_family: GPL3

extra:
  recipe-maintainers:
    - dpryan79
    - johanneskoester
    - bgruening
    - daler
