travis:
  secure:
    BINSTAR_TOKEN: JxCjsL5S+EbdIQxTUYk3cLxcgGlvTDF9mpH52f/JxoKeZx/MwpHWTn/lb9T+Lnh8FZTQJWQJ8Fp+n2HI/8lLpTCZeOzQhb+tpCZgbc8wpsbSxoxvaKPFl5NoZe4FnPe0kUon/nGMPhVfGjHCOd/hUyrWxv54uanK2zNZjV1tz/vJfSaYDimKBz7mAElII0Vzn/BZxBnDlzWUiKtQ3bDDoR3rEAKjXLZ9NCz5QdLhYqnPE9+ise/D6LlTj6F7uBrTK43rkO4vcKiy2f5lJZSul6SYteNTjF2WREf3/n4mdKAoeIF7nho9MHO6WY6qRhQYIbBRiYT08WHTXmeBknjKMN+KW5Hs2/AXgeKOqVBo7phSWS1rr3AOgOwgYMjNH2WACfZy6C7M4Yu5wI/43z9o+Udl9cTDUa3dxtDZ55YTF9S06q0UOL7919ddd1KiOWeNmoV67diZUgOKKAGQfSWRlqAzsNEoT++Zreqazf1DhAefwAxkmJSyvzaxHK7g6hNiaKnF3UtPJyQ6Gnb2xHbjVPq91y4cdx41NPlFMlO4+2o2HX3erAPqAS0xSa+hk8rA8XCbYe6Tynv6Yptam4x/1jW+XdFGY0gHO5HvvGH+oHIYH/w6sOlWaS6+G0AGyalhh71V6zllE0gTxx867XysQ+zjaRQGEtb5HcmTqbMGAlY=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
